FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    libvirt-dev \
    pkg-config \
    qemu-utils \
    libvirt-clients \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir libvirt-python==10.0.0

COPY . .

CMD ["celery", "-A", "workers.celery_app", "worker", "--loglevel=info"]
